project_id = "proj-port-dash"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[studio]
enabled = true

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["http://127.0.0.1:5173"]
