/** Target application contract for MIG-03. Database records remain normalized. */
export const PROJECT_STATUSES = ['Not Started', 'On Track', 'At Risk', 'Overdue', 'Completed'] as const
export const PROJECT_TYPES = ['Key Project', 'BAU Project', 'Unassigned'] as const
export const DEPARTMENTS = ['Infra & Ops', 'Corp Systems', 'Cyber Security', 'Digital Workspace'] as const
export const ACTIVITY_CATEGORIES = ['Initiation', 'Planning', 'Execution', 'Monitoring/Testing', 'Closing'] as const
export const RAID_TYPES = ['Risk', 'Assumption', 'Issue', 'Dependency'] as const
export const RAID_STATUSES = ['Open', 'Mitigated', 'Closed'] as const
export const TASK_STATUSES = ['Pending', 'In Progress', 'Blocked', 'Completed'] as const
export const AUDIT_ACTIONS = ['CREATE', 'UPDATE', 'DELETE', 'COMMENT'] as const
export const AUDIT_ENTITY_TYPES = ['project', 'activity', 'task', 'raid_item', 'activity_comment', 'raid_comment'] as const

export type ProjectStatus = (typeof PROJECT_STATUSES)[number]
export type ProjectType = (typeof PROJECT_TYPES)[number]
export type Department = (typeof DEPARTMENTS)[number]
export type ActivityCategory = (typeof ACTIVITY_CATEGORIES)[number]
export type RaidType = (typeof RAID_TYPES)[number]
export type RaidStatus = (typeof RAID_STATUSES)[number]
export type TaskStatus = (typeof TASK_STATUSES)[number]
export type AuditAction = (typeof AUDIT_ACTIONS)[number]
export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[number]
export type ActivityLevel = 0 | 1 | 2

/** UUID text generated by the database. */
export type PortfolioId = string
/** YYYY-MM-DD calendar date. */
export type DateString = string
/** ISO-8601 timestamp. */
export type TimestampString = string
/** Exact decimal text returned for a PostgreSQL numeric value. */
export type MoneyDecimal = string

interface RecordMetadata {
  id: PortfolioId
  createdAt: TimestampString
  updatedAt: TimestampString
}

export interface Project extends RecordMetadata {
  legacyId: string | null
  name: string
  sponsor: string
  manager: string
  techLead: string
  teamMembers: string
  objective: string
  scope: string
  budgetAmount: MoneyDecimal
  actualSpendAmount: MoneyDecimal
  /** Required uppercase three-letter ISO 4217 currency code for both project amounts. */
  currencyCode: string
  overallStatus: ProjectStatus
  department: Department
  projectType: ProjectType
}

export interface Activity extends RecordMetadata {
  legacyId: string | null
  projectId: PortfolioId
  name: string
  startDate: DateString
  endDate: DateString
  status: ProjectStatus
  isMilestone: boolean
  category: ActivityCategory
  level: ActivityLevel
  sortOrder: number
}

export interface RaidItem extends RecordMetadata {
  legacyId: string | null
  projectId: PortfolioId
  type: RaidType
  description: string
  owner: string
  status: RaidStatus
  startDate: DateString | null
  endDate: DateString | null
}

export interface Task extends RecordMetadata {
  legacyId: string | null
  projectId: PortfolioId
  date: DateString
  name: string
  details: string
  status: TaskStatus
}

interface Comment extends RecordMetadata {
  authorUserId: PortfolioId
  authorEmailSnapshot: string
  commentText: string
}

export interface ActivityComment extends Comment {
  activityId: PortfolioId
}

export interface RaidComment extends Comment {
  raidItemId: PortfolioId
}

export interface AuditLog {
  id: PortfolioId
  occurredAt: TimestampString
  actorUserId: PortfolioId
  actorEmailSnapshot: string
  action: AuditAction
  entityType: AuditEntityType
  entityId: PortfolioId
  entityLabel: string
  details: string | null
}

/** Normalized bundle used by fixtures and future repository/API adapters. */
export interface PortfolioData {
  projects: readonly Project[]
  activities: readonly Activity[]
  raidItems: readonly RaidItem[]
  tasks: readonly Task[]
  activityComments: readonly ActivityComment[]
  raidComments: readonly RaidComment[]
  auditLogs: readonly AuditLog[]
}
